{% set data = load_setuptools()%}
package:
  name: arraymanagement
  version: 0.2

source:
  git_url: https://github.com/ContinuumIO/ArrayManagement
  git_tag: "v0.2"

requirements:
  build:
    - python
    - pandas
    - pytables
    - numpy

  run:
    - python
    - numpy
    - pandas

test:
  imports:
    - numpy
    - pandas

  commands:
    - py.test

about:
  home: https://github.com/ContinuumIO/ArrayManagement
  license: BSD
