{% set data = load_setuptools()%}
package:
  name: pyramid_mako
  version: 1.0.2

source:
  git_url: https://github.com/Pylons/pyramid_mako
  git_tag: "1.0.2"

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - pyramid

test:
  imports:
    - pyramid

  commands:

about:
  home: https://github.com/Pylons/pyramid_mako
  license: BSD 3-Clause 
  license_file: LICENSE.txt
  summary: Pyramid debug toolbar.
  description: |
    pyramid_mako is a set of bindings that makes templates written for
    the Mako templating system work under the Pyramid web framework.
  dev_url: https://github.com/Pylons/pyramid_mako
  doc_url: https://docs.pylonsproject.org/projects/pyramid-mako/en/latest/
