{% set data = load_setuptools()%}
package:
  name: xmlrpc2
  version: 0.3.1

source:
  git_url: https://github.com/dstufft/xmlrpc2
  git_tag: "v0.3.1"

requirements:
  build:
    - python
    - setuptools
  run:
    - python

about:
  home: https://github.com/dstufft/xmlrpc2
  license: BSD 2-Clause
  license_file: LICENSE
  summary: Revamped xmlrpc library for Python.
  description: |
    Revamped xmlrpc library for Python.
  dev_url: https://github.com/dstufft/xmlrpc2
  doc_url: https://github.com/dstufft/xmlrpc2
  doc_source_url: https://github.com/dstufft/xmlrpc2
