{% set data = load_setuptools()%}
package:
  name: pyramid_debugtoolbar
  version: 4.3

source:
  git_url: https://github.com/Pylons/pyramid_debugtoolbar
  git_tag: "4.3"

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - pyramid

test:
  imports:
    - pyramid

  commands:

about:
  home: https://github.com/Pylons/pyramid_debugtoolbar
  license: BSD 3-Clause 
  license_file: LICENSE.txt
  summary: Pyramid debug toolbar.
  description: |
     pyramid_debugtoolbar provides a debug toolbar useful while
     you're developing your Pyramid application.
  dev_url: https://github.com/Pylons/pyramid_debugtoolbar
  doc_url: http://docs.pylonsproject.org/projects/pyramid-debugtoolbar/en/latest/
