{% set data = load_setuptools()%}
package:
  name: pyramid_chameleon
  version: 0.3

source:
  git_url: https://github.com/Pylons/pyramid_chameleon
  git_tag: "0.3"

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - pyramid

test:
  imports:
    - pyramid

  commands:

about:
  home: https://github.com/Pylons/pyramid_chameleon
  license: Custom
  license_file: LICENSE.txt
  summary: Chameleon template compiler for pyramid.
  description: |
    pyramid_chameleon is a set of bindings that make templates written for
    the Chameleon templating system work under the Pyramid web framework.
  dev_url: https://github.com/Pylons/pyramid_chameleon
  doc_url: http://docs.pylonsproject.org/projects/pyramid_chameleon/en/latest/
