{% set data = load_setuptools()%}
package:
  name: pyopengl-accelerate
  version: 3.1.0

source:
  url: https://pypi.python.org/packages/d9/74/293aa8794f2f236186d19e61c5548160bfe159c996ba01ed9144c89ee8ee/PyOpenGL-accelerate-3.1.0.tar.gz
  md5: 489338a4818fa63ea54ff3de1b48995c

requirements:
  build:
    - python
    - setuptools
  run:
    - python

about:
  home: http://pyopengl.sourceforge.net/
  license: BSD
  license_file: license.txt
  summary: Acceleration code for PyOpenGL.
  description: |
    This set of C (Cython) extensions provides acceleration of common
    operations for slow points in PyOpenGL 3.x.
  dev_url: http://pyopengl.sourceforge.net/
  doc_url: http://pyopengl.sourceforge.net/documentation/index.html
