{% set data = load_setuptools()%}
package:
  name: nb_config_manager
  version: 0.1.3

source:
  git_url: https://github.com/Anaconda-Platform/nb_config_manager.git
  git_tag: "v0.1.3"

requirements:
  build:
    - python
  run:
    - python

about:
  home: https://github.com/Anaconda-Platform/nb_config_manager.git
  license: BSD 3-Clause
  license_file: LICENSE
  summary: custom config manager being used to simplify the deployment of continuum notebook extensions.
  description: |
    Package for using an EnvironmentConfigManager able to read not only
    the user config space (config_dir) but also the environment space.
  dev_url: https://github.com/Anaconda-Platform/nb_config_manager
  doc_url: https://github.com/Anaconda-Platform/nb_config_manager
